services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_MARKET_API_URL: "http://localhost:4000"
    ports:
      - "3000:3000"
    depends_on:
      - market
    restart: unless-stopped
  market:
    build:
      context: ./services/market-data-service
      args:
        FRONTEND_URL: "http://20.198.243.7:3000"
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    restart: unless-stopped
