services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_MARKET_API_URL: "http://localhost:4001"
    ports:
      - "3001:3001"
    depends_on:
      - market
    restart: unless-stopped
  market:
    build:
      context: ./services/market-data-service
      args:
        FRONTEND_URL: "http://localhost:3001"
    environment:
      - PORT=4001
    ports:
      - "4001:4001"
    restart: unless-stopped
